// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eSuCo7EbvvTT4cAOXf6WXSkKLsqDlJ8',
    appId: '1:978703539752:web:ba16c2ba4b7978e468df1d',
    messagingSenderId: '978703539752',
    projectId: 'crud-operationswithfirebase',
    authDomain: 'crud-operationswithfirebase.firebaseapp.com',
    storageBucket: 'crud-operationswithfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6S6rwgvSHv5aVGWIxMHL6yF0mz35zK0',
    appId: '1:978703539752:android:d0af6e07c5e1289368df1d',
    messagingSenderId: '978703539752',
    projectId: 'crud-operationswithfirebase',
    storageBucket: 'crud-operationswithfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRAHsD_xQkwYgTSHpGcZ1q4ysi78S1tA',
    appId: '1:978703539752:ios:eb3b809b8753d29868df1d',
    messagingSenderId: '978703539752',
    projectId: 'crud-operationswithfirebase',
    storageBucket: 'crud-operationswithfirebase.appspot.com',
    iosClientId: '978703539752-0l0md9ovohmd6fl04gd4prgnffd2efum.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudoperationswithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLRAHsD_xQkwYgTSHpGcZ1q4ysi78S1tA',
    appId: '1:978703539752:ios:23a3efbed90e5aee68df1d',
    messagingSenderId: '978703539752',
    projectId: 'crud-operationswithfirebase',
    storageBucket: 'crud-operationswithfirebase.appspot.com',
    iosClientId: '978703539752-6v0llce5k8ka44pv9ji17ij50o4pabaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudoperationswithfirebase.RunnerTests',
  );
}
